#spring.application.name=AgriculturalWarehouseManagement
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/managerwarehouse?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
#server:
#  servlet:
#    context-path: /AgriculturalWarehouseManagementApplication
