spring:
  datasource:
    url: jdbc:mysql://localhost:3306/managerwarehouse?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh

    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true # Bật auto-restart để hỗ trợ hot-reload trong phát triển

  web:
    resources:
      static-locations:
        - classpath:/static/
       # - classpath:/static/Frontend/
        - file:D:/Project SWP391/SWP391/AgriculturalWarehouseManagement/src/main/resources/static/
      #        - file:D:/FU Learning/25-Summer/SWP391/QuanLyKhoNongSan/SWP391/AgriculturalWarehouseManagement/src/main/resources/static/
      cache:
        period: 0 # Tắt bộ đệm tài nguyên tĩnh

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework: DEBUG
    com.example.warehouse: DEBUG

app:
  upload:
    product-dir: D:/Uploads

server:
  servlet:
    context-path: /AgriculturalWarehouseManagementApplication