spring:
  datasource:
    url: jdbc:mysql://localhost:3306/managerwarehouse
    username: root
    password: 123456 # Thêm mật khẩu nếu cần, để trống nếu root không có mật khẩu
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true # Bật auto-restart để hỗ trợ hot-reload trong phát triển

  web:
    resources:
      static-locations:
        - file:D:/FU Learning/25-Summer/SWP391/QuanLyKhoNongSan/SWP391/AgriculturalWarehouseManagement/src/main/resources/static/
        - classpath:/static/
      cache:
        period: 0 # Tắt bộ đệm tài nguyên tĩnh

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework: DEBUG
    com.example.warehouse: DEBUG