

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/managerwarehouse
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  logging:
    level:
      org.springframework: DEBUG
      com.yourpackage: DEBUG