spring:
  datasource:
    url: jdbc:mysql://localhost:3306/managerwarehouse?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh

    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true # Bật auto-restart để hỗ trợ hot-reload trong phát triển

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework: DEBUG
    com.example.warehouse: DEBUG

app:
  upload:
    product-dir: D:/Uploads

server:
  servlet:
    context-path: /AgriculturalWarehouseManagementApplication