server:
  servlet:
    context-path: /AgriculturalWarehouseManagement

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/managerwarehouse
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenhoanganh712004qp@gmail.com
    password: okvk uaqv cltb umwg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
project:
  name: AgriculturalWarehouseManagement
debug: true