#spring.application.name=AgriculturalWarehouseManagement
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/managerwarehouse?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#server:
#  servlet:
#    context-path: /AgriculturalWarehouseManagementApplication
